#!/usr/bin/env python3
"""
Project-scoped long-term memory helper for the Code Factory (stdlib only, zero LLM tokens).

`memory/` is the durable memory of ONE target project — the project named by the
`repo_path` field of the task, NOT the factory itself. These subcommands make that
ownership explicit and machine-checkable:

  name  --repo <path>            print the project name = basename of the resolved path.
  init  --repo <deploy_root>     create memory/change-log.md and memory/summary.md from the
                                 canonical templates, but ONLY if they are missing; existing
                                 files are never overwritten or modified, not even partially.
  check --repo <deploy_root>     verify that memory belongs to exactly one project: the
                                 `project:` values of the journal records must agree with
                                 each other, with the declaration in memory/summary.md and —
                                 by default — with project_name(--repo). Memory owned by
                                 another project is an ERROR carrying a `rename` hint;
                                 --no-owner-check drops only that basename comparison, and
                                 --expect <name> replaces the expected name explicitly.
                                 Legacy memory without a `project:` declaration stays a
                                 warning, never an error. The memory format v2 (see
                                 change_log_template) is enforced on the records of a
                                 current-generation factory: they must carry a well-formed
                                 `run_id` AND a provenance mark in `decisions` and in
                                 `results`; records that predate the format and records
                                 without `project:` stay warnings, never errors.
  rename --repo <path> --to <n>  deterministically rewrite the `project:` field of every
                                 journal record and the `project:` declaration of the summary
                                 to <n> (atomic, idempotent: a second run changes nothing and
                                 reports 0 rewritten records). Records without the field stay
                                 legacy; `project:` examples inside the templates' fenced code
                                 blocks are never touched.
  backlog --repo <root>          fold the WHOLE journal into the set of items that are still open:
                                 every `unfinished` item with severity=critical or follow_up=true,
                                 in file order, minus the items closed by a `closed:` block of any
                                 record (matched by the normalized `item` text, whitespace
                                 collapsed and case-insensitive); a record closes an item with
                                 `- item: <text>` + the mandatory `evidence: <command/log/
                                 file:line>`. Each open item is printed with its source record
                                 (timestamp + factory_version): an item left open by a record that
                                 carries no `closed:` block at all is legacy drift — history that
                                 was never reconciled. `--json` prints the report machine-readably.
                                 `--check` exits 1 (naming the reason) while any item is open and
                                 on every invalid `closed:` element — one without `evidence:` or
                                 one naming an item that no record ever declared as open; the
                                 validation of the `closed:` blocks runs always, on any record.
  compact-check --before <f> --after <f>
                                 verify that every unfinished item with severity=critical or
                                 follow_up=true of <f> is still present in the compacted <f>
                                 (matched by the `item` field); every dropped item is an error.
  validate-fix-tasks <file>      validate the fix-task file generated by a security_audit run
                                 (see references/security-audit.md): a YAML list of tasks, each
                                 carrying the required factory-task fields. A schema violation
                                 is an error naming the offending line.

The templates carry the canonical markers required by scripts/check_factory_model.py and
declare `project: <name>`; `check` falls back to that declaration while the journal has no
records yet, so a fresh memory is never mistaken for a legacy one. `<name>` defaults to the
basename of the resolved deploy root; `init --project <name>` overrides it, e.g. when the
task's `repo_path` points to a SUBDIRECTORY of the deploy root — memory/ still lives in the
deploy root, but the project is named after that subdirectory.

Canon of the closing protocol (see the change-log template): an unfinished item NEVER disappears
silently. It is either carried as debt, or closed by a `closed:` element whose `evidence:` names a
real proof (command, test, log, `file:line`); a `closed:` element without evidence does not close
anything, and `backlog --check` fails on it, exactly as it fails on an open item. So `open: 0` is
the only accepted state, and every historical item that was never closed shows up as legacy drift.

Exit codes: 0 = OK, 1 = FAIL (memory mixes projects, belongs to an unexpected project, a record
of the current generation violates the memory format v2, compaction dropped a critical/follow_up
item, `backlog --check` found an open item or an invalid `closed:` element, or a fix-task file
violates its schema). This script imports nothing from the factory:
it runs from anywhere.
"""
from __future__ import annotations

import argparse
import json
import os
import pathlib
import re
import sys

CHANGE_LOG_MARKER = "<!-- code-factory-memory: change-log -->"
SUMMARY_MARKER = "<!-- code-factory-memory: summary -->"
ENTRY_RE = re.compile(r"^##\s+\d{4}-\d{2}-\d{2}")
# Top-level `key: value` field; lines starting with indentation (unfinished items) never match.
FIELD_RE = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*):\s*(.*)$")
# One `unfinished` item and its sub-fields (indented under `unfinished:`).
ITEM_RE = re.compile(r"^\s*-\s*item:\s*(.*)$")
ITEM_FIELD_RE = re.compile(r"^\s*(reason|severity|follow_up):\s*(.*)$")
# Item blocks of a record body: `unfinished` (the debt) and `closed` (the closing protocol).
ITEM_SECTIONS = ("unfinished", "closed")
# The sub-field of a `closed:` element: the mandatory proof of the closure.
CLOSED_FIELD_RE = re.compile(r"^\s*(evidence):\s*(.*)$")
# `## Current state` of memory/summary.md and the factory version it claims as current.
SUMMARY_STATE_HEADING = "## Current state"
CLAIMED_VERSION_RE = re.compile(r"\bv(\d+\.\d+\.\d+)\b")
# The YAML subset of a generated fix-task file: `- title:` starts a task, indented `key:`
# lines are its fields, indented `- value` lines are the items of the current field.
FIX_TASK_RE = re.compile(r"^(?P<indent>\s*)-\s+(?P<key>[A-Za-z_][A-Za-z0-9_]*):\s*(?P<val>.*)$")
FIX_FIELD_RE = re.compile(r"^(?P<indent>\s*)(?P<key>[A-Za-z_][A-Za-z0-9_]*):\s*(?P<val>.*)$")
FIX_LIST_RE = re.compile(r"^(?P<indent>\s*)-\s+(?P<val>.*)$")

# Memory format v2 (introduced after factory 12.8.0): `run_id` (see scripts/run_id.py) and a
# provenance mark — `[verified: <evidence>]` or `[inferred]` — in `decisions` and `results`.
# A record must carry them once it comes from a factory NEWER than MEMORY_V2_AFTER, or as soon
# as it already carries one of the v2 fields (so a half-migrated record is caught as well).
RUN_ID_RE = re.compile(r"^\d{8}-[0-9a-f]{8}$")
PROVENANCE_RE = re.compile(r"\[verified:[^\[\]]+\]|\[inferred\]")
MEMORY_V2_AFTER = (12, 8, 0)
VERSION_RE = re.compile(r"^(\d+)\.(\d+)\.(\d+)$")

LEGACY_NO_PROJECT = "(legacy, no project field)"
# Task types of the factory task format (see references/security-audit.md, section 4).
TASK_TYPES = ("implement", "review", "refactor", "security_audit")
# Required by every generated fix task, per references/security-audit.md, section 4.
FIX_TASK_REQUIRED = ("title", "description", "task_type", "acceptance_criteria")


def project_name(repo: str | pathlib.Path) -> str:
    """Return the project name: basename of the resolved path."""
    return pathlib.Path(repo).resolve().name


def owner_hints(repo: pathlib.Path, owner: str, expected: str) -> list[str]:
    """Fix suggestions printed next to an owner mismatch (see the module docstring).

    Two legitimate cases exist: the memory was migrated from another deployment directory
    (fix it with `rename`), or the project name is intentionally the basename of a
    SUBDIRECTORY of the deploy root (then `--expect <name>` / `--no-owner-check` are correct).
    """
    return [
        "hint: the expected owner is the basename of the resolved --repo path",
        f"hint: migrate the memory with: memory_project.py rename --repo \"{repo}\" "
        f"--to {expected}",
        f"hint: or, if the owner '{owner}' is intentional (repo_path points to a "
        f"subdirectory of the deploy root), re-run with --expect {owner} or --no-owner-check",
    ]


def write_text_atomic(path: pathlib.Path, text: str) -> None:
    """Write `text` to `path` atomically (same-dir temp file + os.replace), newlines as-is."""
    tmp = path.with_name(path.name + ".tmp")
    with tmp.open("w", encoding="utf-8", newline="") as fh:
        fh.write(text)
    os.replace(tmp, path)


def read_text_raw(path: pathlib.Path) -> str:
    """Read a file without newline translation, so rewriting keeps the original line endings."""
    with path.open("r", encoding="utf-8", newline="") as fh:
        return fh.read()


def split_eol(line: str) -> tuple[str, str]:
    """Split a raw line into (body, eol) so a rewrite can preserve the file's line endings."""
    for eol in ("\r\n", "\n"):
        if line.endswith(eol):
            return line[: -len(eol)], eol
    return line, ""


def change_log_template(project: str) -> str:
    """Canonical `memory/change-log.md` skeleton (append-only journal, no entries yet)."""
    return f"""# Change Log — {project}

{CHANGE_LOG_MARKER}

Append-only journal of the factory's runs on the project `{project}`. One entry per completed
task (success OR FAILED), written by the single writer — the main agent at the end of the task.
Entries are never deleted or reordered; once the threshold (50 entries) is exceeded the old ones
are folded into `memory/summary.md`, and the last 20 entries stay here.

The memory belongs to ONE project — the one named in the task's `repo_path` field. The
`project:` field = the basename of the `repo_path` directory (for this journal — `{project}`).
Different `project:` values in one journal are an error; entries without the `project:` field
are legacy (a warning, not an error). Checked by: `scripts/memory_project.py check` and
`scripts/check_factory_model.py`.

Entry format (flat, verified by `scripts/check_factory_model.py`):

```
## <ISO timestamp> — <title>
title: <string>
project: <project name — basename of the task's repo_path, always {project} here>
timestamp: <ISO8601 date>
run_id: <YYYYMMDD-8hex — run identifier, scripts/run_id.py>
branch: <branch or "(none)">
commit: <sha or "(none)">
task_type: implement | review | refactor | security_audit
goal: <brief goal>
changed_files: <list separated by "; ">
created_files: <list separated by "; ">
results: integration=<PASS|FAIL|SKIP>; regression=<...>; business=<...>; review=<approve|request_changes|SKIP> — key results with a [verified: <command/test/log>] or [inferred] mark
decisions: <decisions made; every key claim carries a [verified: <command/test/log>] or [inferred] mark>
assumptions: <assumptions>
models_used: analyzer=<model>; coder=<model>; tester=<model>; reviewer=<model>
factory_version: <X.Y.Z — factory version at the time of the run>
unfinished: no unfinished items
closed: (optional) one element per closed item — item: <item text> + evidence: <evidence>
```

A one-line example of an entry (one entry — one block, fields line by line):
`title: Short title | project: {project} | timestamp: 2026-01-01T00:00:00+0300 | task_type: implement | ...`

**Format v2 (introduced after v12.8.0): `run_id` + provenance marks.** The `run_id` field is the
run identifier (`YYYYMMDD-<8 hex>`, see `scripts/run_id.py`); it ties the entry to the run's
artifacts. Every KEY claim of a new entry in the `decisions` and `results` fields carries an
inline mark right in the field value:
`[verified: <command/test/log proving the claim>]` — the claim is verified by evidence, or
`[inferred]` — inferred but not verified. Example:
`results: integration=PASS [verified: .code-factory/logs/code-results.md]; review=approve [inferred]`.
An entry written by a factory newer than v12.8.0 without `run_id` (or with a `run_id` not
matching `^\\d{{8}}-[0-9a-f]{{8}}$`) or without a mark in `decisions`/`results` is a format
ERROR; entries without the `project:` field and entries written by a factory no newer than
v12.8.0 are legacy (a warning, not an error). Verified by `scripts/memory_project.py check` and
`scripts/check_factory_model.py`.

If there is debt, the single `unfinished:` line is replaced by a multi-line list; every element
requires 4 fields (`item`, `reason`, `severity` critical|warning|info, `follow_up` true|false):

```
unfinished:
  - item: code reviewer findings accepted as-is
    reason: reviewer budget exhausted
    severity: warning
    follow_up: false
```

The `unfinished` section is filled in for every entry, even when empty (the explicit `no
unfinished items` marker). During compaction the elements with severity=critical or
follow_up=true are always preserved. Entries without `project`, `unfinished` or
`factory_version` pass validation with a warning (not an error) — this is legacy compatibility.

**Closing protocol: an item NEVER disappears without evidence.** When a debt is closed (fixed in
code or deemed obsolete), the closing entry carries a `closed:` block next to `unfinished:` —
one element per closed item; every element requires `item` (the item text it is matched to the
original by) and `evidence` (the command/test/log/`file:line` proving the closure):

```
closed:
  - item: code reviewer findings accepted as-is
    evidence: scripts/memory_project.py:120 -> exit 0 (closed v12.10.1)
```

A closure without `evidence:` is invalid, as is a `closed:` element naming an item that no
journal entry ever declared: both cases are an error of `scripts/memory_project.py backlog
--check` (on par with open items). The reconciliation runs over ALL journal entries, so
historical debts can be closed too: an item that was never closed stays open and is printed by
`backlog` as legacy drift together with its source entry. Memory actuality check:
`python scripts/memory_project.py backlog --repo . --check`.
"""


def summary_template(project: str, repo_path: str) -> str:
    """Canonical `memory/summary.md` skeleton (declares the owning project + empty sections)."""
    return f"""# Project Summary — {project}

{SUMMARY_MARKER}
project: {project}
repo_path: {repo_path}

A compact summary of the project. Folded from the old entries of `memory/change-log.md` during
compaction (threshold of 50 entries) and read at the start of every task so the project history
is not replayed from scratch.

## Current state

## Key decisions

## Recent history
"""


def cmd_name(args: argparse.Namespace) -> int:
    print(project_name(args.repo))
    return 0


def cmd_init(args: argparse.Namespace) -> int:
    root = pathlib.Path(args.repo).resolve()
    project = args.project or root.name
    memdir = root / "memory"
    memdir.mkdir(parents=True, exist_ok=True)
    templates = {
        "change-log.md": change_log_template(project),
        # The declared repo_path is always the resolved root, exactly like the project name.
        "summary.md": summary_template(project, str(root)),
    }
    for name, text in templates.items():
        path = memdir / name
        if path.is_file():
            print(f"exists: {path}")
            continue
        write_text_atomic(path, text)
        print(f"created: {path}")
    return 0


def journal_records(change_log: pathlib.Path) -> list[tuple[str, dict[str, str]]]:
    """Return (heading, top-level fields) of every journal record, in file order.

    Only lines after a dated `## ` heading count, and only non-indented `key: value` lines are
    fields — so the template's fenced examples and the `unfinished` sub-fields are never read
    as fields.
    """
    records: list[tuple[str, dict[str, str]]] = []
    heading: str | None = None
    fields: dict[str, str] = {}
    for line in change_log.read_text(encoding="utf-8").splitlines():
        if ENTRY_RE.match(line):
            if heading is not None:
                records.append((heading, fields))
            heading, fields = line.strip(), {}
            continue
        if heading is None:
            continue
        m = FIELD_RE.match(line)
        if m:
            fields[m.group(1)] = m.group(2).strip()
    if heading is not None:
        records.append((heading, fields))
    return records


def journal_projects(change_log: pathlib.Path) -> list[str]:
    """Return the distinct non-empty top-level `project:` values of all journal entries."""
    found: list[str] = []
    for _, fields in journal_records(change_log):
        value = fields.get("project", "")
        if value and value not in found:
            found.append(value)
    return found


def version_after(factory_version: str, base: tuple[int, int, int] = MEMORY_V2_AFTER) -> bool:
    """True when `factory_version` (X.Y.Z) is strictly newer than `base`."""
    m = VERSION_RE.match(factory_version.strip())
    return bool(m) and tuple(int(g) for g in m.groups()) > base


def is_v2_record(fields: dict[str, str]) -> bool:
    """True when a journal record has to satisfy the memory format v2 (see the template).

    That is the case once the record comes from a factory version NEWER than MEMORY_V2_AFTER,
    or as soon as it already carries a v2 field — `run_id` or a provenance mark — so a
    half-migrated record is never silently accepted. Records without `project:` are legacy and
    are only warned about, exactly like the other newer keys; records written before the format
    stay as they are.
    """
    if not fields.get("project", "").strip():
        return False
    return (version_after(fields.get("factory_version", ""))
            or "run_id" in fields
            or any(PROVENANCE_RE.search(fields.get(f, "")) for f in ("decisions", "results")))


def record_format_issues(change_log: pathlib.Path) -> tuple[list[str], list[str]]:
    """Return (errors, warnings) of the memory format v2 over a whole journal.

    A v2 record must carry a well-formed `run_id` and at least one provenance mark in
    `decisions` AND in `results`; a miss is an error there, a warning in a legacy record.
    """
    errors: list[str] = []
    warnings: list[str] = []
    for heading, fields in journal_records(change_log):
        problems: list[str] = []
        run_id = fields.get("run_id", "").strip()
        if not run_id:
            problems.append("missing or empty key 'run_id'")
        elif not RUN_ID_RE.match(run_id):
            problems.append(f"invalid run_id '{run_id}' (expected YYYYMMDD-<8 hex>)")
        for field in ("decisions", "results"):
            if not PROVENANCE_RE.search(fields.get(field, "")):
                problems.append(f"no provenance mark '[verified: <evidence>]' or '[inferred]' "
                                f"in '{field}'")
        if not problems:
            continue
        if is_v2_record(fields):
            errors += [f"entry '{heading}': {p}" for p in problems]
        elif not fields.get("project", "").strip():
            warnings += [f"entry '{heading}': {p} (legacy format)" for p in problems]
    return errors, warnings


def entry_count(change_log: pathlib.Path) -> int:
    """Number of journal entries (lines starting a dated `## <timestamp>` record)."""
    return sum(1 for line in change_log.read_text(encoding="utf-8").splitlines()
               if ENTRY_RE.match(line))


def summary_project(summary: pathlib.Path) -> str:
    """Return the `project:` declared by memory/summary.md ("" when it declares none).

    Only the declaration area counts — right after the canonical marker and before the first
    `## ` section — so a `project: <name>` example inside a fenced code block is never mistaken
    for a declaration (same rule as scripts/check_factory_model.py).
    """
    if not summary.is_file():
        return ""
    lines = summary.read_text(encoding="utf-8").splitlines()
    start = next((i + 1 for i, ln in enumerate(lines) if SUMMARY_MARKER in ln), None)
    if start is None:
        return ""
    for line in lines[start:]:
        if line.startswith("## "):
            break
        m = FIELD_RE.match(line)
        if m and m.group(1) == "project":
            return m.group(2).strip()
    return ""


def cmd_check(args: argparse.Namespace) -> int:
    root = pathlib.Path(args.repo).resolve()
    change_log = root / "memory" / "change-log.md"
    if not change_log.is_file():
        print("note: memory/change-log.md not found (fresh project)")
        return 0

    projects = journal_projects(change_log)
    if len(projects) > 1:
        print("FAIL - memory mixes projects: " + ", ".join(sorted(projects)), file=sys.stderr)
        return 1

    journal_owner = projects[0] if projects else ""
    declared = summary_project(root / "memory" / "summary.md")
    if journal_owner and declared and journal_owner != declared:
        print(f"FAIL - memory/summary.md declares project '{declared}' but the journal "
              f"belongs to '{journal_owner}'", file=sys.stderr)
        for hint in owner_hints(root, declared, project_name(root)):
            print(hint, file=sys.stderr)
        return 1

    # Owner = the journal's own value; while the journal has no records yet, the declaration
    # in summary.md is authoritative (otherwise a fresh memory would look like a legacy one).
    owner = journal_owner or declared
    if not declared:
        print(f"WARN - memory/summary.md does not declare 'project: <name>' (legacy memory, "
              f"owner '{owner or LEGACY_NO_PROJECT}')", file=sys.stderr)
    # Enforced ownership: memory belongs to the project named after the resolved --repo path.
    # A legacy memory (no declared owner at all) stays a warning, never an error; --expect
    # overrides the expected name and --no-owner-check drops only this comparison.
    expected = args.expect or ("" if args.no_owner_check else project_name(root))
    if expected and owner and owner != expected:
        print(f"FAIL - memory belongs to project '{owner}', expected '{expected}'",
              file=sys.stderr)
        for hint in owner_hints(root, owner, expected):
            print(hint, file=sys.stderr)
        return 1

    # Memory format v2 (run_id + provenance marks) of the records themselves: an error for the
    # records of a current-generation factory, a warning for legacy records without `project:`.
    fmt_errors, fmt_warnings = record_format_issues(change_log)
    for warning in fmt_warnings:
        print(f"WARN - {warning}", file=sys.stderr)
    if fmt_errors:
        print("FAIL - memory record format v2 violated:", file=sys.stderr)
        for error in fmt_errors:
            print(f"  {error}", file=sys.stderr)
        return 1

    print(f"ok - memory belongs to project '{owner or LEGACY_NO_PROJECT}' "
          f"({entry_count(change_log)} entries)")
    return 0


def rewrite_journal_project(text: str, name: str) -> tuple[str, int]:
    """Rewrite the `project:` field of every journal record to `name`.

    Only record bodies count (lines after a dated `## ` heading), so the `project:` examples in
    the template's fenced code blocks are never touched. Records without the field stay legacy
    and are not counted, which makes a repeated run a no-op (idempotent). Returns
    (text, number of records actually rewritten); the file's line endings are preserved.
    """
    out: list[str] = []
    rewritten = 0
    in_entry = False
    for raw in text.splitlines(keepends=True):
        body, eol = split_eol(raw)
        if ENTRY_RE.match(body):
            in_entry = True
        elif in_entry:
            m = FIELD_RE.match(body)
            if m and m.group(1) == "project" and m.group(2).strip() != name:
                body = f"project: {name}"
                rewritten += 1
        out.append(body + eol)
    return "".join(out), rewritten


def rewrite_summary_project(text: str, name: str) -> tuple[str, str]:
    """Rewrite the `project:` declaration of summary.md; return (text, state).

    state is "absent" when the file declares no project at all (legacy memory), "unchanged" when
    it already names `name`, and "updated" otherwise. Only the declaration area counts — right
    after the canonical marker and before the first `## ` section — exactly like summary_project.
    """
    lines = text.splitlines(keepends=True)
    start = next((i + 1 for i, ln in enumerate(lines) if SUMMARY_MARKER in ln), None)
    if start is None:
        return text, "absent"
    for i in range(start, len(lines)):
        body, eol = split_eol(lines[i])
        if body.startswith("## "):
            break
        m = FIELD_RE.match(body)
        if m and m.group(1) == "project":
            if m.group(2).strip() == name:
                return text, "unchanged"
            lines[i] = f"project: {name}" + eol
            return "".join(lines), "updated"
    return text, "absent"


def cmd_rename(args: argparse.Namespace) -> int:
    new = args.to.strip()
    if len(new.split()) != 1:
        print("FAIL - --to must be a single non-empty project name", file=sys.stderr)
        return 1
    root = pathlib.Path(args.repo).resolve()
    memdir = root / "memory"
    change_log = memdir / "change-log.md"
    summary = memdir / "summary.md"
    if not change_log.is_file() and not summary.is_file():
        print(f"FAIL - no memory/change-log.md or memory/summary.md under {root}", file=sys.stderr)
        return 1

    if change_log.is_file():
        text, rewritten = rewrite_journal_project(read_text_raw(change_log), new)
        if rewritten:
            write_text_atomic(change_log, text)
        print(f"{change_log}: {rewritten} record(s) rewritten to project '{new}'")
    else:
        print(f"note: {change_log} not found (nothing to rewrite)")

    if summary.is_file():
        text, state = rewrite_summary_project(read_text_raw(summary), new)
        if state == "updated":
            write_text_atomic(summary, text)
        print(f"{summary}: project declaration {state}")
    else:
        print(f"note: {summary} not found (nothing to rewrite)")

    print(f"ok - memory owner is now '{new}' (expected by project_name({root}))")
    return 0


def unfinished_items(path: pathlib.Path) -> list[dict[str, str]]:
    """Return every `unfinished` item of a journal or a compacted summary, in file order.

    Works on both file kinds: an item is any `- item: <text>` line, and the following
    `reason:`/`severity:`/`follow_up:` lines belong to it (same rule as
    scripts/check_factory_model.py). Items inside a `closed:` block are skipped — they are
    closures, not debt, and counting them as "present" would weaken a compaction check. An item
    that belongs to no top-level block key (e.g. one under a `## Unfinished` heading) is still read,
    so files written before the `closed:` protocol keep behaving exactly as they did.
    """
    items: list[dict[str, str]] = []
    cur: dict[str, str] | None = None
    in_closed = False
    for line in path.read_text(encoding="utf-8").splitlines():
        m = FIELD_RE.match(line)
        if m:
            in_closed = m.group(1) == "closed" and not m.group(2).strip()
        elif line.startswith("## "):
            in_closed = False               # a new section always ends the `closed:` block
        m = ITEM_RE.match(line)
        if m:
            if in_closed:
                continue
            cur = {"item": m.group(1).strip()}
            items.append(cur)
            continue
        m = ITEM_FIELD_RE.match(line)
        if m and cur is not None:
            cur[m.group(1)] = m.group(2).strip()
    return items


def must_survive_compaction(items: list[dict[str, str]]) -> list[str]:
    """The `item` values a compaction must keep: severity=critical or follow_up=true."""
    return [i["item"] for i in items
            if i["item"] and (i.get("severity", "").lower() == "critical"
                              or i.get("follow_up", "").lower() == "true")]


def cmd_compact_check(args: argparse.Namespace) -> int:
    before, after = pathlib.Path(args.before), pathlib.Path(args.after)
    for path in (before, after):
        if not path.is_file():
            print(f"FAIL - file not found: {path}", file=sys.stderr)
            return 1

    required = must_survive_compaction(unfinished_items(before))
    present = {item["item"] for item in unfinished_items(after)}
    missing = [item for item in required if item not in present]
    if missing:
        print(f"FAIL - compaction dropped {len(missing)} of {len(required)} "
              f"critical/follow_up item(s):", file=sys.stderr)
        for item in missing:
            print(f"  - {item}", file=sys.stderr)
        return 1

    print(f"ok - compaction preserved all {len(required)} critical/follow_up item(s) "
          f"({len(present)} item(s) in {after.name})")
    return 0


def journal_blocks(change_log: pathlib.Path) -> list[dict]:
    """Parse the journal into records carrying their fields AND their item blocks.

    Every record is `{"heading": str, "fields": {key: value}, "blocks": {"unfinished": [...],
    "closed": [...]}}`. An item block is opened by the top-level key of that name with an EMPTY
    value (`unfinished:`, `closed:`) and ends at the next top-level `key: value` line; inside it a
    `- item: <text>` line starts an element and the indented sub-fields belong to it (`reason`,
    `severity`, `follow_up` — and `evidence` for a `closed:` element). Lines before the first
    record and the template's fenced examples are never read, so the format examples stay inert.
    """
    records: list[dict] = []
    cur: dict | None = None
    section: str | None = None
    item: dict[str, str] | None = None
    for line in change_log.read_text(encoding="utf-8").splitlines():
        if ENTRY_RE.match(line):
            cur = {"heading": line.strip(), "fields": {},
                   "blocks": {s: [] for s in ITEM_SECTIONS}}
            records.append(cur)
            section, item = None, None
            continue
        if cur is None:
            continue
        m = FIELD_RE.match(line)
        if m:
            key, value = m.group(1), m.group(2).strip()
            cur["fields"][key] = value
            section = key if not value and key in ITEM_SECTIONS else None
            item = None
            continue
        if section is None:
            continue
        m = ITEM_RE.match(line)
        if m:
            item = {"item": m.group(1).strip()}
            cur["blocks"][section].append(item)
            continue
        m = ITEM_FIELD_RE.match(line) or CLOSED_FIELD_RE.match(line)
        if m and item is not None:
            item[m.group(1)] = m.group(2).strip()
    return records


def normalize_item(text: str) -> str:
    """Item identity for matching: whitespace collapsed, case-insensitive (see `backlog`)."""
    return " ".join(text.split()).casefold()


def is_open_item(item: dict[str, str]) -> bool:
    """True when an `unfinished` item is debt that stays open: severity=critical or follow_up=true.

    The same predicate as `must_survive_compaction`, so "must survive a compaction" and "must
    appear in the backlog" can never drift apart.
    """
    return bool(must_survive_compaction([item]))


def record_timestamp(record: dict) -> str:
    """The `timestamp:` of a record, falling back to the date that opens its heading."""
    stamp = record["fields"].get("timestamp", "").strip()
    return stamp or (record["heading"][3:].split() or [""])[0]


def backlog_report(root: pathlib.Path) -> dict:
    """Fold a whole journal into the open item set and the validity of its `closed:` blocks.

    The fold runs over every record in FILE ORDER: a record first contributes its open items
    (severity=critical or follow_up=true) and then applies its own `closed:` elements, so an item
    declared again after an earlier closure is open again. An element closes the item whose
    normalized text matches one declared as open SOMEWHERE in the journal — an element naming an
    unknown item, or one without `evidence:`, is an error regardless of the record's age (the
    validation is never gated by a version) and closes NOTHING, so a broken closure can never hide
    a debt. Open items keep the record that declared them, which is what makes an unreconciled
    history readable as legacy drift.

    Returns `{"open": int, "items": [...], "closed": int, "legacy_drift": int, "errors": [...],
    "warnings": [...]}`; `items` keeps the file order of the declaring record.
    """
    change_log = root / "memory" / "change-log.md"
    records = journal_blocks(change_log) if change_log.is_file() else []

    declared: set[str] = set()
    for record in records:
        for item in record["blocks"]["unfinished"]:
            if is_open_item(item) and item["item"]:
                declared.add(normalize_item(item["item"]))

    open_items: dict[str, dict] = {}
    errors: list[dict] = []
    closed_total = 0
    for record in records:
        heading = record["heading"]
        version = record["fields"].get("factory_version", "")
        has_closed_block = bool(record["blocks"]["closed"])
        for item in record["blocks"]["unfinished"]:
            if is_open_item(item) and item["item"]:
                open_items[normalize_item(item["item"])] = {
                    "item": item["item"],
                    "source": heading,
                    "timestamp": record_timestamp(record),
                    "factory_version": version,
                    "severity": item.get("severity", ""),
                    "follow_up": item.get("follow_up", ""),
                    "source_closed": has_closed_block,
                }
        for closed in record["blocks"]["closed"]:
            closed_total += 1
            text = closed.get("item", "")
            if not text:
                errors.append({"kind": "closed-without-item", "record": heading, "item": "",
                               "message": f"entry '{heading}': a 'closed:' element carries no "
                                          f"'item:' text"})
                continue
            key = normalize_item(text)
            evidence = closed.get("evidence", "").strip()
            if not evidence:
                errors.append({"kind": "closed-without-evidence", "record": heading, "item": text,
                               "message": f"entry '{heading}': closed item '{text}' carries no "
                                          f"'evidence:' (closing without evidence is invalid)"})
            if key not in declared:
                errors.append({"kind": "closed-unknown-item", "record": heading, "item": text,
                               "message": f"entry '{heading}': closed item '{text}' matches no "
                                          f"follow_up/critical item of the journal"})
            # Only a VALID closure (evidence + an item the journal declared) actually closes the
            # item: an unsupported `closed:` element leaves the debt open, so it cannot hide it.
            if evidence and key in declared:
                open_items.pop(key, None)

    items = list(open_items.values())
    drift = sum(1 for item in items if not item["source_closed"])
    return {
        "open": len(items),
        "closed": closed_total,
        "legacy_drift": drift,
        "items": [{k: v for k, v in item.items() if k != "source_closed"} for item in items],
        "errors": errors,
        "warnings": [],
    }


def current_state_text(summary: pathlib.Path) -> str:
    """Body of the `## Current state` section of memory/summary.md ("" when the section is absent).

    Only that section counts: the rest of the summary (history, key decisions) is allowed to name
    older versions, exactly like the `project:` declaration area rule used by `check`.
    """
    if not summary.is_file():
        return ""
    lines = summary.read_text(encoding="utf-8").splitlines()
    start = next((i + 1 for i, ln in enumerate(lines)
                  if ln.startswith(SUMMARY_STATE_HEADING)), None)
    if start is None:
        return ""
    body: list[str] = []
    for line in lines[start:]:
        if line.startswith("## "):
            break
        body.append(line)
    return "\n".join(body)


def summary_version_warnings(root: pathlib.Path) -> list[str]:
    """WARN when `## Current state` claims a factory version other than the repo's VERSION.

    The version the section claims as CURRENT is its first `vX.Y.Z` mention (e.g. "Factory
    v12.10.0: …"); the older versions it name-drops later are history and never warn. Nothing is
    claimed (or there is no VERSION file) — nothing to compare, so no warning.
    """
    version_file = root / "VERSION"
    if not version_file.is_file():
        return []
    version = version_file.read_text(encoding="utf-8").strip()
    claimed = CLAIMED_VERSION_RE.search(current_state_text(root / "memory" / "summary.md"))
    if not version or not claimed or claimed.group(1) == version:
        return []
    return [f"memory/summary.md '{SUMMARY_STATE_HEADING}' claims factory version "
            f"v{claimed.group(1)} but VERSION says {version} — the summary is stale, refresh "
            f"'{SUMMARY_STATE_HEADING}'"]


def cmd_backlog(args: argparse.Namespace) -> int:
    root = pathlib.Path(args.repo).resolve()
    report = backlog_report(root)
    report["warnings"] = summary_version_warnings(root)

    if args.json:
        print(json.dumps(report, ensure_ascii=False, indent=2))
    else:
        print(f"open: {report['open']}")
        for item in report["items"]:
            print(f"  - {item['item']} "
                  f"[source: {item['timestamp']}, "
                  f"factory_version={item['factory_version'] or '?'}]")
        if report["closed"]:
            print(f"closed: {report['closed']} item(s) with evidence")
        if report["legacy_drift"]:
            print(f"note: {report['legacy_drift']} of these item(s) come from record(s) without a "
                  f"'closed:' block (legacy drift) — close them in a new record with 'closed:' "
                  f"+ 'evidence:'")

    for warning in report["warnings"]:
        print(f"WARN - {warning}", file=sys.stderr)
    # The `closed:` blocks are validated on every run, but they only fail under `--check`: without
    # it they are reported, exactly like the open items themselves.
    verdict = "FAIL" if args.check else "WARN"
    for problem in report["errors"]:
        print(f"{verdict} - {problem['message']}", file=sys.stderr)
    if not args.check:
        return 0

    if report["open"]:
        print(f"FAIL - memory backlog is not actual: {report['open']} open item(s), oldest source "
              f"{report['items'][0]['timestamp']}", file=sys.stderr)
        for item in report["items"]:
            print(f"  - {item['item']} [source: {item['timestamp']}]", file=sys.stderr)
    if report["open"] or report["errors"]:
        print("FAIL - backlog --check requires 'open: 0' and a valid closing protocol (every "
              "'closed:' element carrying 'evidence:' and naming an existing item)",
              file=sys.stderr)
        return 1

    print(f"ok - backlog is actual (open: 0, {report['closed']} closed item(s) with evidence)")
    return 0


def unquote(value: str) -> str:
    """Drop one pair of matching surrounding quotes from a scalar YAML value."""
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        return value[1:-1]
    return value


def parse_fix_tasks(text: str) -> list[dict]:
    """Parse the YAML subset of a generated fix-task file (no PyYAML in the factory).

    The file is a flat sequence of task mappings — `- title: ...` starts a task, deeper indented
    `key: value` lines are its fields, and deeper indented `- value` lines are the items of the
    current field (acceptance_criteria, models, commit_exclude). A top-level `tasks:` mapping is
    accepted too. Each task is {"line": int, "fields": {key: (value, line)}, "lists": {key: […]}}.
    """
    tasks: list[dict] = []
    task_indent: int | None = None
    cur: dict | None = None
    cur_key = ""
    for lineno, raw in enumerate(text.splitlines(), 1):
        line = raw.rstrip()
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        indent = len(line) - len(line.lstrip())
        m = FIX_TASK_RE.match(line)
        if m and (task_indent is None or indent == task_indent):
            if task_indent is None:
                task_indent = indent
            cur = {"line": lineno, "fields": {}, "lists": {}}
            tasks.append(cur)
            cur_key = ""
            cur["fields"][m.group("key")] = (unquote(m.group("val").strip()), lineno)
            continue
        if cur is None:
            continue  # preamble before the first task (e.g. a version comment)
        lm = FIX_LIST_RE.match(line)
        if lm and cur_key:
            cur["lists"].setdefault(cur_key, []).append(unquote(lm.group("val").strip()))
            continue
        fm = FIX_FIELD_RE.match(line)
        if fm and indent > (task_indent or 0):
            cur_key = fm.group("key")
            val = unquote(fm.group("val").strip())
            if val:
                cur["fields"][cur_key] = (val, lineno)
            else:
                cur["lists"].setdefault(cur_key, [])
    return tasks


def validate_fix_tasks(text: str) -> tuple[list[dict], list[str]]:
    """Return (tasks, schema errors naming the offending lines) of a generated fix-task file."""
    tasks = parse_fix_tasks(text)
    if not tasks:
        return [], ["line 1: no fix tasks found (expected a YAML list, each task starting with "
                    "'- title:')"]

    errors: list[str] = []
    for index, task in enumerate(tasks, 1):
        line = task["line"]
        fields, lists = task["fields"], task["lists"]
        title = fields.get("title", ("", line))[0]
        for key in FIX_TASK_REQUIRED:
            present = bool(fields.get(key, ("", 0))[0] or lists.get(key))
            if not present:
                errors.append(f"line {line}: task {index} '{title}' missing required field "
                              f"'{key}'")
        task_type = fields.get("task_type")
        if task_type and task_type[0] not in TASK_TYPES:
            errors.append(f"line {task_type[1]}: task {index} '{title}' has invalid task_type "
                          f"'{task_type[0]}' (expected one of {', '.join(TASK_TYPES)})")
    return tasks, errors


def cmd_validate_fix_tasks(args: argparse.Namespace) -> int:
    path = pathlib.Path(args.file)
    if not path.is_file():
        print(f"FAIL - file not found: {path}", file=sys.stderr)
        return 1

    tasks, errors = validate_fix_tasks(path.read_text(encoding="utf-8"))
    if errors:
        print("FAIL - invalid fix-task file:", file=sys.stderr)
        for err in errors:
            print(f"  {err}", file=sys.stderr)
        return 1

    print(f"ok - {path.name} is a valid fix-task file ({len(tasks)} task(s))")
    return 0


def use_utf8_output() -> None:
    """Force UTF-8 on stdout/stderr so the help survives being piped or redirected.

    A Windows console defaults to a legacy code page (cp866/cp1251) and the help text carries a
    non-ASCII character (`—`, the em dash), which that codec cannot encode: `print_help()` would
    raise UnicodeEncodeError and the user would get a traceback instead of the help.
    `errors="replace"` keeps a stream that cannot be reconfigured from ever raising.
    """
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, ValueError):      # an old interpreter or a replaced stream
            pass


def main() -> int:
    use_utf8_output()
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="command", required=True)

    p_name = sub.add_parser("name", help="print the project name (basename of the resolved path)")
    p_name.add_argument("--repo", required=True, help="Path to the target project")
    p_name.set_defaults(func=cmd_name)

    p_init = sub.add_parser("init", help="create memory files if they are missing (never overwrites)")
    p_init.add_argument("--repo", required=True, help="Deploy root that holds memory/")
    p_init.add_argument("--project", default="",
                        help="Project name (default: basename of the resolved deploy root)")
    p_init.set_defaults(func=cmd_init)

    p_check = sub.add_parser("check", help="verify that memory belongs to a single project")
    p_check.add_argument("--repo", required=True, help="Deploy root that holds memory/")
    p_check.add_argument("--expect", default="",
                         help="Expected project name (default: basename of the resolved --repo)")
    p_check.add_argument("--no-owner-check", action="store_true",
                         help="Do not compare the owner with the basename of the resolved --repo "
                              "(only --expect and the summary/journal agreement are checked)")
    p_check.set_defaults(func=cmd_check)

    p_rename = sub.add_parser("rename",
                              help="rewrite the project name in the journal and the summary")
    p_rename.add_argument("--repo", required=True, help="Deploy root that holds memory/")
    p_rename.add_argument("--to", required=True, help="New project name")
    p_rename.set_defaults(func=cmd_rename)

    p_backlog = sub.add_parser("backlog",
                               help="fold the open critical/follow_up items and their closures")
    p_backlog.add_argument("--repo", required=True, help="Deploy root that holds memory/")
    p_backlog.add_argument("--check", action="store_true",
                           help="Exit 1 unless 'open: 0' and every 'closed:' element is valid "
                                "(carries 'evidence:' and names an existing item)")
    p_backlog.add_argument("--json", action="store_true", help="Print the report as JSON")
    p_backlog.set_defaults(func=cmd_backlog)

    p_compact = sub.add_parser("compact-check",
                               help="verify that compaction kept critical/follow_up items")
    p_compact.add_argument("--before", required=True, help="Journal or summary before compaction")
    p_compact.add_argument("--after", required=True, help="Compacted summary (or journal)")
    p_compact.set_defaults(func=cmd_compact_check)

    p_fix = sub.add_parser("validate-fix-tasks",
                           help="validate a generated security_audit fix-task file")
    p_fix.add_argument("file", help="Path to the generated fix-tasks.yaml")
    p_fix.set_defaults(func=cmd_validate_fix_tasks)

    args = ap.parse_args()
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
