#!/usr/bin/env python3
"""
Project-scoped long-term memory helper for the Code Factory (stdlib only, zero LLM tokens).

`memory/` is the durable memory of ONE target project — the project named by the
`repo_path` field of the task, NOT the factory itself. These subcommands make that
ownership explicit and machine-checkable:

  name  --repo <path>            print the project name = basename of the resolved path.
  init  --repo <deploy_root>     create memory/change-log.md and memory/summary.md from the
                                 canonical templates, but ONLY if they are missing; existing
                                 files are never overwritten or modified, not even partially.
  check --repo <deploy_root>     verify that memory belongs to exactly one project: the
                                 `project:` values of the journal records must agree with
                                 each other, with the declaration in memory/summary.md and —
                                 by default — with project_name(--repo). Memory owned by
                                 another project is an ERROR carrying a `rename` hint;
                                 --no-owner-check drops only that basename comparison, and
                                 --expect <name> replaces the expected name explicitly.
                                 Legacy memory without a `project:` declaration stays a
                                 warning, never an error. The memory format v2 (see
                                 change_log_template) is enforced on the records of a
                                 current-generation factory: they must carry a well-formed
                                 `run_id` AND a provenance mark in `decisions` and in
                                 `results`; records that predate the format and records
                                 without `project:` stay warnings, never errors.
  rename --repo <path> --to <n>  deterministically rewrite the `project:` field of every
                                 journal record and the `project:` declaration of the summary
                                 to <n> (atomic, idempotent: a second run changes nothing and
                                 reports 0 rewritten records). Records without the field stay
                                 legacy; `project:` examples inside the templates' fenced code
                                 blocks are never touched.
  compact-check --before <f> --after <f>
                                 verify that every unfinished item with severity=critical or
                                 follow_up=true of <f> is still present in the compacted <f>
                                 (matched by the `item` field); every dropped item is an error.
  validate-fix-tasks <file>      validate the fix-task file generated by a security_audit run
                                 (see references/security-audit.md): a YAML list of tasks, each
                                 carrying the required factory-task fields. A schema violation
                                 is an error naming the offending line.

The templates carry the canonical markers required by scripts/check_factory_model.py and
declare `project: <name>`; `check` falls back to that declaration while the journal has no
records yet, so a fresh memory is never mistaken for a legacy one. `<name>` defaults to the
basename of the resolved deploy root; `init --project <name>` overrides it, e.g. when the
task's `repo_path` points to a SUBDIRECTORY of the deploy root — memory/ still lives in the
deploy root, but the project is named after that subdirectory.

Exit codes: 0 = OK, 1 = FAIL (memory mixes projects, belongs to an unexpected project, a record
of the current generation violates the memory format v2, compaction dropped a critical/follow_up
item, or a fix-task file violates its schema). This script imports nothing from the factory:
it runs from anywhere.
"""
from __future__ import annotations

import argparse
import os
import pathlib
import re
import sys

CHANGE_LOG_MARKER = "<!-- code-factory-memory: change-log -->"
SUMMARY_MARKER = "<!-- code-factory-memory: summary -->"
ENTRY_RE = re.compile(r"^##\s+\d{4}-\d{2}-\d{2}")
# Top-level `key: value` field; lines starting with indentation (unfinished items) never match.
FIELD_RE = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*):\s*(.*)$")
# One `unfinished` item and its sub-fields (indented under `unfinished:`).
ITEM_RE = re.compile(r"^\s*-\s*item:\s*(.*)$")
ITEM_FIELD_RE = re.compile(r"^\s*(reason|severity|follow_up):\s*(.*)$")
# The YAML subset of a generated fix-task file: `- title:` starts a task, indented `key:`
# lines are its fields, indented `- value` lines are the items of the current field.
FIX_TASK_RE = re.compile(r"^(?P<indent>\s*)-\s+(?P<key>[A-Za-z_][A-Za-z0-9_]*):\s*(?P<val>.*)$")
FIX_FIELD_RE = re.compile(r"^(?P<indent>\s*)(?P<key>[A-Za-z_][A-Za-z0-9_]*):\s*(?P<val>.*)$")
FIX_LIST_RE = re.compile(r"^(?P<indent>\s*)-\s+(?P<val>.*)$")

# Memory format v2 (introduced after factory 12.8.0): `run_id` (see scripts/run_id.py) and a
# provenance mark — `[verified: <evidence>]` or `[inferred]` — in `decisions` and `results`.
# A record must carry them once it comes from a factory NEWER than MEMORY_V2_AFTER, or as soon
# as it already carries one of the v2 fields (so a half-migrated record is caught as well).
RUN_ID_RE = re.compile(r"^\d{8}-[0-9a-f]{8}$")
PROVENANCE_RE = re.compile(r"\[verified:[^\[\]]+\]|\[inferred\]")
MEMORY_V2_AFTER = (12, 8, 0)
VERSION_RE = re.compile(r"^(\d+)\.(\d+)\.(\d+)$")

LEGACY_NO_PROJECT = "(legacy, no project field)"
# Task types of the factory task format (see references/security-audit.md, section 4).
TASK_TYPES = ("implement", "review", "refactor", "security_audit")
# Required by every generated fix task, per references/security-audit.md, section 4.
FIX_TASK_REQUIRED = ("title", "description", "task_type", "acceptance_criteria")


def project_name(repo: str | pathlib.Path) -> str:
    """Return the project name: basename of the resolved path."""
    return pathlib.Path(repo).resolve().name


def owner_hints(repo: pathlib.Path, owner: str, expected: str) -> list[str]:
    """Fix suggestions printed next to an owner mismatch (see the module docstring).

    Two legitimate cases exist: the memory was migrated from another deployment directory
    (fix it with `rename`), or the project name is intentionally the basename of a
    SUBDIRECTORY of the deploy root (then `--expect <name>` / `--no-owner-check` are correct).
    """
    return [
        "hint: the expected owner is the basename of the resolved --repo path",
        f"hint: migrate the memory with: memory_project.py rename --repo \"{repo}\" "
        f"--to {expected}",
        f"hint: or, if the owner '{owner}' is intentional (repo_path points to a "
        f"subdirectory of the deploy root), re-run with --expect {owner} or --no-owner-check",
    ]


def write_text_atomic(path: pathlib.Path, text: str) -> None:
    """Write `text` to `path` atomically (same-dir temp file + os.replace), newlines as-is."""
    tmp = path.with_name(path.name + ".tmp")
    with tmp.open("w", encoding="utf-8", newline="") as fh:
        fh.write(text)
    os.replace(tmp, path)


def read_text_raw(path: pathlib.Path) -> str:
    """Read a file without newline translation, so rewriting keeps the original line endings."""
    with path.open("r", encoding="utf-8", newline="") as fh:
        return fh.read()


def split_eol(line: str) -> tuple[str, str]:
    """Split a raw line into (body, eol) so a rewrite can preserve the file's line endings."""
    for eol in ("\r\n", "\n"):
        if line.endswith(eol):
            return line[: -len(eol)], eol
    return line, ""


def change_log_template(project: str) -> str:
    """Canonical `memory/change-log.md` skeleton (append-only journal, no entries yet)."""
    return f"""# Change Log — {project}

{CHANGE_LOG_MARKER}

Append-only журнал прогонов фабрики по проекту `{project}`. Одна запись на завершённую
задачу (успех ИЛИ FAILED), пишет единственный писатель — главный агент в конце задачи.
Записи не удаляются и не переупорядочиваются; при превышении порога (50 записей) старые
сворачиваются в `memory/summary.md`, здесь остаётся последние 20 записей.

Память принадлежит ОДНОМУ проекту — тому, что указан в поле `repo_path` задачи. Поле
`project:` = basename каталога `repo_path` (для этого журнала — `{project}`). Разные
значения `project:` в одном журнале — ошибка; записи без поля `project:` — legacy
(предупреждение, не ошибка). Проверка: `scripts/memory_project.py check` и
`scripts/check_factory_model.py`.

Формат записи (плоский, проверяется `scripts/check_factory_model.py`):

```
## <ISO timestamp> — <title>
title: <строка>
project: <имя проекта — basename(repo_path задачи), здесь всегда {project}>
timestamp: <ISO8601 дата>
run_id: <YYYYMMDD-8hex — идентификатор прогона, scripts/run_id.py>
branch: <ветка или "(none)">
commit: <sha или "(none)">
task_type: implement | review | refactor | security_audit
goal: <краткая цель>
changed_files: <список через "; ">
created_files: <список через "; ">
results: integration=<PASS|FAIL|SKIP>; regression=<...>; business=<...>; review=<approve|request_changes|SKIP> — ключевые результаты с меткой [verified: <команда/тест/лог>] или [inferred]
decisions: <принятые решения; каждое ключевое утверждение с меткой [verified: <команда/тест/лог>] или [inferred]>
assumptions: <допущения>
models_used: analyzer=<модель>; coder=<модель>; tester=<модель>; reviewer=<модель>
factory_version: <X.Y.Z — версия фабрики на момент прогона>
unfinished: нет незавершённых элементов
```

Однострочный пример записи (одна запись — один блок, поля построчно):
`title: Короткий заголовок | project: {project} | timestamp: 2026-01-01T00:00:00+0300 | task_type: implement | ...`

**Формат v2 (введён после v12.8.0): `run_id` + provenance-метки.** Поле `run_id` — идентификатор
прогона (`YYYYMMDD-<8 hex>`, см. `scripts/run_id.py`), по нему запись связывается с артефактами
прогона. Каждое КЛЮЧЕВОЕ утверждение новой записи в полях `decisions` и `results` несёт
инлайн-метку прямо в значении поля:
`[verified: <команда/тест/лог, подтверждающий утверждение>]` — утверждение проверено
доказательством, или `[inferred]` — выведено, но не проверено. Пример:
`results: integration=PASS [verified: .code-factory/logs/code-results.md]; review=approve [inferred]`.
Запись, написанная фабрикой новее v12.8.0, без `run_id` (или с `run_id` не по формату
`^\\d{{8}}-[0-9a-f]{{8}}$`) либо без метки в `decisions`/`results` — ОШИБКА формата; записи без
поля `project:` и записи, написанные фабрикой не новее v12.8.0, — legacy (предупреждение, не
ошибка). Проверяют `scripts/memory_project.py check` и `scripts/check_factory_model.py`.

Если долг есть — вместо одной строки `unfinished:` пишется многострочный список; для каждого
элемента обязательны 4 поля (`item`, `reason`, `severity` critical|warning|info, `follow_up`
true|false):

```
unfinished:
  - item: замечания код-ревьюера приняты как есть
    reason: бюджет ревьюера исчерпан
    severity: warning
    follow_up: false
```

Секция `unfinished` заполняется обязательно при каждой записи, даже если пуста (явный маркер
`нет незавершённых элементов`). При компакции элементы с severity=critical или follow_up=true
сохраняются обязательно. Записи без `project`, `unfinished` или `factory_version` проходят
валидацию с предупреждением (не ошибкой) — это legacy-совместимость.
"""


def summary_template(project: str, repo_path: str) -> str:
    """Canonical `memory/summary.md` skeleton (declares the owning project + empty sections)."""
    return f"""# Project Summary — {project}

{SUMMARY_MARKER}
project: {project}
repo_path: {repo_path}

Сжатая сводка проекта. Сворачивается из старых записей `memory/change-log.md` при компакции
(порог 50 записей) и читается в начале каждой задачи, чтобы не выводить историю проекта заново.

## Current state

## Key decisions

## Recent history
"""


def cmd_name(args: argparse.Namespace) -> int:
    print(project_name(args.repo))
    return 0


def cmd_init(args: argparse.Namespace) -> int:
    root = pathlib.Path(args.repo).resolve()
    project = args.project or root.name
    memdir = root / "memory"
    memdir.mkdir(parents=True, exist_ok=True)
    templates = {
        "change-log.md": change_log_template(project),
        # The declared repo_path is always the resolved root, exactly like the project name.
        "summary.md": summary_template(project, str(root)),
    }
    for name, text in templates.items():
        path = memdir / name
        if path.is_file():
            print(f"exists: {path}")
            continue
        write_text_atomic(path, text)
        print(f"created: {path}")
    return 0


def journal_records(change_log: pathlib.Path) -> list[tuple[str, dict[str, str]]]:
    """Return (heading, top-level fields) of every journal record, in file order.

    Only lines after a dated `## ` heading count, and only non-indented `key: value` lines are
    fields — so the template's fenced examples and the `unfinished` sub-fields are never read
    as fields.
    """
    records: list[tuple[str, dict[str, str]]] = []
    heading: str | None = None
    fields: dict[str, str] = {}
    for line in change_log.read_text(encoding="utf-8").splitlines():
        if ENTRY_RE.match(line):
            if heading is not None:
                records.append((heading, fields))
            heading, fields = line.strip(), {}
            continue
        if heading is None:
            continue
        m = FIELD_RE.match(line)
        if m:
            fields[m.group(1)] = m.group(2).strip()
    if heading is not None:
        records.append((heading, fields))
    return records


def journal_projects(change_log: pathlib.Path) -> list[str]:
    """Return the distinct non-empty top-level `project:` values of all journal entries."""
    found: list[str] = []
    for _, fields in journal_records(change_log):
        value = fields.get("project", "")
        if value and value not in found:
            found.append(value)
    return found


def version_after(factory_version: str, base: tuple[int, int, int] = MEMORY_V2_AFTER) -> bool:
    """True when `factory_version` (X.Y.Z) is strictly newer than `base`."""
    m = VERSION_RE.match(factory_version.strip())
    return bool(m) and tuple(int(g) for g in m.groups()) > base


def is_v2_record(fields: dict[str, str]) -> bool:
    """True when a journal record has to satisfy the memory format v2 (see the template).

    That is the case once the record comes from a factory version NEWER than MEMORY_V2_AFTER,
    or as soon as it already carries a v2 field — `run_id` or a provenance mark — so a
    half-migrated record is never silently accepted. Records without `project:` are legacy and
    are only warned about, exactly like the other newer keys; records written before the format
    stay as they are.
    """
    if not fields.get("project", "").strip():
        return False
    return (version_after(fields.get("factory_version", ""))
            or "run_id" in fields
            or any(PROVENANCE_RE.search(fields.get(f, "")) for f in ("decisions", "results")))


def record_format_issues(change_log: pathlib.Path) -> tuple[list[str], list[str]]:
    """Return (errors, warnings) of the memory format v2 over a whole journal.

    A v2 record must carry a well-formed `run_id` and at least one provenance mark in
    `decisions` AND in `results`; a miss is an error there, a warning in a legacy record.
    """
    errors: list[str] = []
    warnings: list[str] = []
    for heading, fields in journal_records(change_log):
        problems: list[str] = []
        run_id = fields.get("run_id", "").strip()
        if not run_id:
            problems.append("missing or empty key 'run_id'")
        elif not RUN_ID_RE.match(run_id):
            problems.append(f"invalid run_id '{run_id}' (expected YYYYMMDD-<8 hex>)")
        for field in ("decisions", "results"):
            if not PROVENANCE_RE.search(fields.get(field, "")):
                problems.append(f"no provenance mark '[verified: <evidence>]' or '[inferred]' "
                                f"in '{field}'")
        if not problems:
            continue
        if is_v2_record(fields):
            errors += [f"entry '{heading}': {p}" for p in problems]
        elif not fields.get("project", "").strip():
            warnings += [f"entry '{heading}': {p} (legacy format)" for p in problems]
    return errors, warnings


def entry_count(change_log: pathlib.Path) -> int:
    """Number of journal entries (lines starting a dated `## <timestamp>` record)."""
    return sum(1 for line in change_log.read_text(encoding="utf-8").splitlines()
               if ENTRY_RE.match(line))


def summary_project(summary: pathlib.Path) -> str:
    """Return the `project:` declared by memory/summary.md ("" when it declares none).

    Only the declaration area counts — right after the canonical marker and before the first
    `## ` section — so a `project: <name>` example inside a fenced code block is never mistaken
    for a declaration (same rule as scripts/check_factory_model.py).
    """
    if not summary.is_file():
        return ""
    lines = summary.read_text(encoding="utf-8").splitlines()
    start = next((i + 1 for i, ln in enumerate(lines) if SUMMARY_MARKER in ln), None)
    if start is None:
        return ""
    for line in lines[start:]:
        if line.startswith("## "):
            break
        m = FIELD_RE.match(line)
        if m and m.group(1) == "project":
            return m.group(2).strip()
    return ""


def cmd_check(args: argparse.Namespace) -> int:
    root = pathlib.Path(args.repo).resolve()
    change_log = root / "memory" / "change-log.md"
    if not change_log.is_file():
        print("note: memory/change-log.md not found (fresh project)")
        return 0

    projects = journal_projects(change_log)
    if len(projects) > 1:
        print("FAIL - memory mixes projects: " + ", ".join(sorted(projects)), file=sys.stderr)
        return 1

    journal_owner = projects[0] if projects else ""
    declared = summary_project(root / "memory" / "summary.md")
    if journal_owner and declared and journal_owner != declared:
        print(f"FAIL - memory/summary.md declares project '{declared}' but the journal "
              f"belongs to '{journal_owner}'", file=sys.stderr)
        for hint in owner_hints(root, declared, project_name(root)):
            print(hint, file=sys.stderr)
        return 1

    # Owner = the journal's own value; while the journal has no records yet, the declaration
    # in summary.md is authoritative (otherwise a fresh memory would look like a legacy one).
    owner = journal_owner or declared
    if not declared:
        print(f"WARN - memory/summary.md does not declare 'project: <name>' (legacy memory, "
              f"owner '{owner or LEGACY_NO_PROJECT}')", file=sys.stderr)
    # Enforced ownership: memory belongs to the project named after the resolved --repo path.
    # A legacy memory (no declared owner at all) stays a warning, never an error; --expect
    # overrides the expected name and --no-owner-check drops only this comparison.
    expected = args.expect or ("" if args.no_owner_check else project_name(root))
    if expected and owner and owner != expected:
        print(f"FAIL - memory belongs to project '{owner}', expected '{expected}'",
              file=sys.stderr)
        for hint in owner_hints(root, owner, expected):
            print(hint, file=sys.stderr)
        return 1

    # Memory format v2 (run_id + provenance marks) of the records themselves: an error for the
    # records of a current-generation factory, a warning for legacy records without `project:`.
    fmt_errors, fmt_warnings = record_format_issues(change_log)
    for warning in fmt_warnings:
        print(f"WARN - {warning}", file=sys.stderr)
    if fmt_errors:
        print("FAIL - memory record format v2 violated:", file=sys.stderr)
        for error in fmt_errors:
            print(f"  {error}", file=sys.stderr)
        return 1

    print(f"ok - memory belongs to project '{owner or LEGACY_NO_PROJECT}' "
          f"({entry_count(change_log)} entries)")
    return 0


def rewrite_journal_project(text: str, name: str) -> tuple[str, int]:
    """Rewrite the `project:` field of every journal record to `name`.

    Only record bodies count (lines after a dated `## ` heading), so the `project:` examples in
    the template's fenced code blocks are never touched. Records without the field stay legacy
    and are not counted, which makes a repeated run a no-op (idempotent). Returns
    (text, number of records actually rewritten); the file's line endings are preserved.
    """
    out: list[str] = []
    rewritten = 0
    in_entry = False
    for raw in text.splitlines(keepends=True):
        body, eol = split_eol(raw)
        if ENTRY_RE.match(body):
            in_entry = True
        elif in_entry:
            m = FIELD_RE.match(body)
            if m and m.group(1) == "project" and m.group(2).strip() != name:
                body = f"project: {name}"
                rewritten += 1
        out.append(body + eol)
    return "".join(out), rewritten


def rewrite_summary_project(text: str, name: str) -> tuple[str, str]:
    """Rewrite the `project:` declaration of summary.md; return (text, state).

    state is "absent" when the file declares no project at all (legacy memory), "unchanged" when
    it already names `name`, and "updated" otherwise. Only the declaration area counts — right
    after the canonical marker and before the first `## ` section — exactly like summary_project.
    """
    lines = text.splitlines(keepends=True)
    start = next((i + 1 for i, ln in enumerate(lines) if SUMMARY_MARKER in ln), None)
    if start is None:
        return text, "absent"
    for i in range(start, len(lines)):
        body, eol = split_eol(lines[i])
        if body.startswith("## "):
            break
        m = FIELD_RE.match(body)
        if m and m.group(1) == "project":
            if m.group(2).strip() == name:
                return text, "unchanged"
            lines[i] = f"project: {name}" + eol
            return "".join(lines), "updated"
    return text, "absent"


def cmd_rename(args: argparse.Namespace) -> int:
    new = args.to.strip()
    if len(new.split()) != 1:
        print("FAIL - --to must be a single non-empty project name", file=sys.stderr)
        return 1
    root = pathlib.Path(args.repo).resolve()
    memdir = root / "memory"
    change_log = memdir / "change-log.md"
    summary = memdir / "summary.md"
    if not change_log.is_file() and not summary.is_file():
        print(f"FAIL - no memory/change-log.md or memory/summary.md under {root}", file=sys.stderr)
        return 1

    if change_log.is_file():
        text, rewritten = rewrite_journal_project(read_text_raw(change_log), new)
        if rewritten:
            write_text_atomic(change_log, text)
        print(f"{change_log}: {rewritten} record(s) rewritten to project '{new}'")
    else:
        print(f"note: {change_log} not found (nothing to rewrite)")

    if summary.is_file():
        text, state = rewrite_summary_project(read_text_raw(summary), new)
        if state == "updated":
            write_text_atomic(summary, text)
        print(f"{summary}: project declaration {state}")
    else:
        print(f"note: {summary} not found (nothing to rewrite)")

    print(f"ok - memory owner is now '{new}' (expected by project_name({root}))")
    return 0


def unfinished_items(path: pathlib.Path) -> list[dict[str, str]]:
    """Return every `unfinished` item of a journal or a compacted summary, in file order.

    Works on both file kinds: an item is any `- item: <text>` line, and the following
    `reason:`/`severity:`/`follow_up:` lines belong to it (same rule as
    scripts/check_factory_model.py).
    """
    items: list[dict[str, str]] = []
    cur: dict[str, str] | None = None
    for line in path.read_text(encoding="utf-8").splitlines():
        m = ITEM_RE.match(line)
        if m:
            cur = {"item": m.group(1).strip()}
            items.append(cur)
            continue
        m = ITEM_FIELD_RE.match(line)
        if m and cur is not None:
            cur[m.group(1)] = m.group(2).strip()
    return items


def must_survive_compaction(items: list[dict[str, str]]) -> list[str]:
    """The `item` values a compaction must keep: severity=critical or follow_up=true."""
    return [i["item"] for i in items
            if i["item"] and (i.get("severity", "").lower() == "critical"
                              or i.get("follow_up", "").lower() == "true")]


def cmd_compact_check(args: argparse.Namespace) -> int:
    before, after = pathlib.Path(args.before), pathlib.Path(args.after)
    for path in (before, after):
        if not path.is_file():
            print(f"FAIL - file not found: {path}", file=sys.stderr)
            return 1

    required = must_survive_compaction(unfinished_items(before))
    present = {item["item"] for item in unfinished_items(after)}
    missing = [item for item in required if item not in present]
    if missing:
        print(f"FAIL - compaction dropped {len(missing)} of {len(required)} "
              f"critical/follow_up item(s):", file=sys.stderr)
        for item in missing:
            print(f"  - {item}", file=sys.stderr)
        return 1

    print(f"ok - compaction preserved all {len(required)} critical/follow_up item(s) "
          f"({len(present)} item(s) in {after.name})")
    return 0


def unquote(value: str) -> str:
    """Drop one pair of matching surrounding quotes from a scalar YAML value."""
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        return value[1:-1]
    return value


def parse_fix_tasks(text: str) -> list[dict]:
    """Parse the YAML subset of a generated fix-task file (no PyYAML in the factory).

    The file is a flat sequence of task mappings — `- title: ...` starts a task, deeper indented
    `key: value` lines are its fields, and deeper indented `- value` lines are the items of the
    current field (acceptance_criteria, models, commit_exclude). A top-level `tasks:` mapping is
    accepted too. Each task is {"line": int, "fields": {key: (value, line)}, "lists": {key: […]}}.
    """
    tasks: list[dict] = []
    task_indent: int | None = None
    cur: dict | None = None
    cur_key = ""
    for lineno, raw in enumerate(text.splitlines(), 1):
        line = raw.rstrip()
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        indent = len(line) - len(line.lstrip())
        m = FIX_TASK_RE.match(line)
        if m and (task_indent is None or indent == task_indent):
            if task_indent is None:
                task_indent = indent
            cur = {"line": lineno, "fields": {}, "lists": {}}
            tasks.append(cur)
            cur_key = ""
            cur["fields"][m.group("key")] = (unquote(m.group("val").strip()), lineno)
            continue
        if cur is None:
            continue  # preamble before the first task (e.g. a version comment)
        lm = FIX_LIST_RE.match(line)
        if lm and cur_key:
            cur["lists"].setdefault(cur_key, []).append(unquote(lm.group("val").strip()))
            continue
        fm = FIX_FIELD_RE.match(line)
        if fm and indent > (task_indent or 0):
            cur_key = fm.group("key")
            val = unquote(fm.group("val").strip())
            if val:
                cur["fields"][cur_key] = (val, lineno)
            else:
                cur["lists"].setdefault(cur_key, [])
    return tasks


def validate_fix_tasks(text: str) -> tuple[list[dict], list[str]]:
    """Return (tasks, schema errors naming the offending lines) of a generated fix-task file."""
    tasks = parse_fix_tasks(text)
    if not tasks:
        return [], ["line 1: no fix tasks found (expected a YAML list, each task starting with "
                    "'- title:')"]

    errors: list[str] = []
    for index, task in enumerate(tasks, 1):
        line = task["line"]
        fields, lists = task["fields"], task["lists"]
        title = fields.get("title", ("", line))[0]
        for key in FIX_TASK_REQUIRED:
            present = bool(fields.get(key, ("", 0))[0] or lists.get(key))
            if not present:
                errors.append(f"line {line}: task {index} '{title}' missing required field "
                              f"'{key}'")
        task_type = fields.get("task_type")
        if task_type and task_type[0] not in TASK_TYPES:
            errors.append(f"line {task_type[1]}: task {index} '{title}' has invalid task_type "
                          f"'{task_type[0]}' (expected one of {', '.join(TASK_TYPES)})")
    return tasks, errors


def cmd_validate_fix_tasks(args: argparse.Namespace) -> int:
    path = pathlib.Path(args.file)
    if not path.is_file():
        print(f"FAIL - file not found: {path}", file=sys.stderr)
        return 1

    tasks, errors = validate_fix_tasks(path.read_text(encoding="utf-8"))
    if errors:
        print("FAIL - invalid fix-task file:", file=sys.stderr)
        for err in errors:
            print(f"  {err}", file=sys.stderr)
        return 1

    print(f"ok - {path.name} is a valid fix-task file ({len(tasks)} task(s))")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="command", required=True)

    p_name = sub.add_parser("name", help="print the project name (basename of the resolved path)")
    p_name.add_argument("--repo", required=True, help="Path to the target project")
    p_name.set_defaults(func=cmd_name)

    p_init = sub.add_parser("init", help="create memory files if they are missing (never overwrites)")
    p_init.add_argument("--repo", required=True, help="Deploy root that holds memory/")
    p_init.add_argument("--project", default="",
                        help="Project name (default: basename of the resolved deploy root)")
    p_init.set_defaults(func=cmd_init)

    p_check = sub.add_parser("check", help="verify that memory belongs to a single project")
    p_check.add_argument("--repo", required=True, help="Deploy root that holds memory/")
    p_check.add_argument("--expect", default="",
                         help="Expected project name (default: basename of the resolved --repo)")
    p_check.add_argument("--no-owner-check", action="store_true",
                         help="Do not compare the owner with the basename of the resolved --repo "
                              "(only --expect and the summary/journal agreement are checked)")
    p_check.set_defaults(func=cmd_check)

    p_rename = sub.add_parser("rename",
                              help="rewrite the project name in the journal and the summary")
    p_rename.add_argument("--repo", required=True, help="Deploy root that holds memory/")
    p_rename.add_argument("--to", required=True, help="New project name")
    p_rename.set_defaults(func=cmd_rename)

    p_compact = sub.add_parser("compact-check",
                               help="verify that compaction kept critical/follow_up items")
    p_compact.add_argument("--before", required=True, help="Journal or summary before compaction")
    p_compact.add_argument("--after", required=True, help="Compacted summary (or journal)")
    p_compact.set_defaults(func=cmd_compact_check)

    p_fix = sub.add_parser("validate-fix-tasks",
                           help="validate a generated security_audit fix-task file")
    p_fix.add_argument("file", help="Path to the generated fix-tasks.yaml")
    p_fix.set_defaults(func=cmd_validate_fix_tasks)

    args = ap.parse_args()
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
